name: rick_and_morty
version: 1.0.0+1
description: The Rick and Morty Fan App.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  animated_splash_screen: 1.1.0
  flutter_spinkit: 5.1.0
  intl: 0.17.0
  http: 0.13.4
  infinite_scroll_pagination: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

